# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [88]:
import numpy as np
import random
import scipy.stats as sps
import cv2

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [89]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
#==========
# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print('==========')
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
#==========
print('==========')
print("Матрица 1 =",a)
print('')
print("Матрица 2 =",b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
Матрица 1 = [[0.9382821  0.05485244 0.7846172  ... 0.60366585 0.11376158 0.40335519]
 [0.04425611 0.8793181  0.76668522 ... 0.61812542 0.27118273 0.74070986]
 [0.16167628 0.8264736  0.53211601 ... 0.41556741 0.86226853 0.64106705]
 ...
 [0.06889733 0.79942596 0.09002535 ... 0.10583003 0.39987081 0.04682631]
 [0.95755566 0.64968841 0.47758715 ... 0.93721001 0.48564129 0.70023961]
 [0.04038942 0.73618993 0.83271744 ... 0.08458406 0.28468826 0.38798804]]

Матрица 2 = [[0.1035029  0.47353732 0.14151142 ... 0.64215269 0.69099284 0.69923367]
 [0.01167138 0.03811839 0.7151068  ... 0.46362239 0.64378264 0.90579025]
 [0.57179367 0.64015373 0.59889778 ... 0.52012384 0.7723033  0.7304983 ]
 ...
 [0.51731993 0.55403424 0.74312665 ... 0.89768659 0.45099385 0.35099969]
 [0.18192567 0.65058539 0.69792342 ... 0.71423565 0.34242401 0.00241023]
 [0.77797009 0.34223436 0.12518815 ... 0.25180659 0.43885823 0.89455792]]


Без использования numpy

In [90]:
def mult(a, b):
  # Итоговая матрица res_arr будет содержать результат умножения матриц a и b.
  # Её размерность равна числу строк первой матрицы на число столбцов второй матрицы.
  res_arr = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]
  # Цикл идет по строкам матрицы a.
  for a_value in range(len(a)):
    # Цикл идет по столбцам матрицы b.
    for b_value in range(len(b[0])):
      for common in range(len(b)):
        # Внутри вложенных циклов происходит умножение соответствующих элементов матриц,
        # что соответствует обычной формуле для вычисления результата умножения матриц.
        res_arr[a_value][b_value] += a[a_value][common] * b[common][b_value]
  return res_arr

C использованием numpy

In [91]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [92]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 479 ms, sys: 2.51 ms, total: 481 ms
Wall time: 488 ms


In [93]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 260 µs, sys: 0 ns, total: 260 µs
Wall time: 155 µs


In [94]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4786394331167685e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [95]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.74574076 0.79789809 0.78415096] [0.25435138 0.7448027  0.7386074 ]


In [96]:
def scalar_product(a, b):
  s = sum(ai * bi for ai, bi in zip(a, b)) # zip - для комбинирования элементов векторов.
  return s

In [97]:
def np_scalar_product(a, b):
  s = np.dot(a, b)
  return s

In [98]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# Проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 37 µs, sys: 6 µs, total: 43 µs
Wall time: 46.7 µs
CPU times: user 27 µs, sys: 4 µs, total: 31 µs
Wall time: 34.8 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:**
- Numpy методы эффективнее, потому что они основаны на оптимизированных вычислительных операциях языков Fortran и C.
- В NumPy скорость вычислений выше, чем в чистом Python, особенно при работе с большими массивами данных. Операции в NumPy, как уже было сказано, основаны на оптимизированных вычислительных операциях языков Fortran и C. А это языки низжнего уровня (по отношению к Phyton). Они оптимизированы для работы с массивами, и значительно быстрее, в сравнении с операциями в Python.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [99]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag_elem = np.diag(a)
  even_diag_elem = diag_elem[diag_elem % 2 == 0]
  return even_diag_elem.size > 0 if even_diag_elem.sum() else 0

In [100]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 5, 7, 8, 5],
       [7, 3, 2, 4, 7],
       [6, 9, 4, 1, 4],
       [8, 6, 1, 8, 4],
       [9, 6, 6, 5, 4]])

In [101]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 99 µs, sys: 0 ns, total: 99 µs
Wall time: 104 µs


True

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [102]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
  A = np.array(A)
  # Используем cumsum для вычисления накопленной суммы
  cumsum_A = np.cumsum(A, axis=1)
  # Вычисляем s_k = (x1 + ... + xk) / k для каждого k
  k_values = np.arange(1, A.shape[1] + 1)
  result = cumsum_A / k_values.reshape(1, -1)
  return result

In [103]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[9.11062156e-01 4.31620163e-01 6.97177219e-01 2.97562489e-01
 9.58973915e-01 4.65118572e-01 1.45408062e-01 9.35163608e-01
 5.32813070e-01 4.12052653e-01 1.22943260e-01 1.01827032e-01
 5.16514374e-01 9.69385614e-01 1.04984138e-01 5.86877464e-01
 7.57540611e-01 5.63567482e-01 5.04781082e-01 1.38112884e-01
 1.61884302e-01 7.21303793e-01 8.97590329e-01 4.39750300e-01
 2.46783014e-01 4.63128568e-01 8.61051061e-01 1.71701999e-01
 8.12583050e-01 4.82042240e-01 1.80560474e-01 4.59553814e-01
 6.94744045e-01 7.12126204e-01 1.41565226e-01 2.62524256e-01
 4.64685099e-01 7.66935386e-01 7.29587280e-01 7.75011288e-01
 6.50999233e-01 8.36490718e-01 4.37923780e-02 4.33331961e-01
 8.97818590e-01 3.57114630e-01 5.49473598e-01 7.33647941e-01
 9.89812410e-01 3.68126252e-02 5.37687839e-01 1.26676345e-01
 4.57748174e-01 2.02543310e-01 8.44444399e-01 3.96499834e-01
 9.91383122e-01 3.51459481e-01 4.41327707e-01 5.03846066e-01
 9.53243417e-01 4.45958715e-01 2.97072425e-01 7.80260023e-01
 8.87049443e-01 4.463637

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [104]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
  # Используем функцию groupby из itertools для группировки повторяющихся элементов
  grouped_elements = [(key, len(list(group))) for key, group in groupby(a)]
  x, num = zip(*grouped_elements)
  return np.array(x), np.array(num)

In [105]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 42.2 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [106]:
# функция, решающая задачу с помощью NumPy
def np_transformation(X, a=1):
  # Создаем копию массива X для сохранения оригинала
  x_copy = np.copy(X)
  # Нечётные элементы заменяем на "a", а чётные возводим в куб.
  x_copy[1::2] = a
  x_copy[::2] **= 3
  # Создаем новый массив, в котором элементы записаны в обратном порядке и сольём его с X
  reversed_x_copy = x_copy[::-1]
  result = np.concatenate([X, reversed_x_copy])
  return result

In [107]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 900 µs, sys: 0 ns, total: 900 µs
Wall time: 880 µs
